### ISSUE TITLE
How to include a carousel in a widget

### ISSUE THREAD

**Issue by lyndametref** [diggy/wp-bootstrap-carousel#10]
I have tried to create a widget with a carousel. I used text widget and added the `[carousel post_parent=1]` shortcode to it but it did not work (wordpress 4.4.2). Is there a way to do it?

I also would like to know if it is possible to link the associated post to the carousel image?

**Comment by lyndametref** [comment]
I have managed to have a carousel in a widget by installing the Advanced Text Widget plugin and adding  the proper code in it:

`<?php echo do_shortcode('[display-posts post_type="page" post_parent="13" image_size="medium" bootstrap="1" width=250px]'); ?>`

For my second question I finally understand properly the doc for the use of Display Posts Shortcode and the code above did what I wanted.

**Comment by diggy** [comment]
@lyndametref glad you figured it out. You could also enable shortcode support for widgets by adding following one-liner to your functions.php file:

```
add_filter( 'widget_text', 'do_shortcode' );
```
